import { createSystem, defaultConfig, defineConfig } from "@chakra-ui/react";
import { buttonRecipe } from "./theme/recipe/button.recipe";
import { dialogRecipe } from "./theme/recipe/dialog.slotRecipe";

const config = defineConfig({
  theme: {
    recipes: {
      button: buttonRecipe,
      // dialog: dialogRecipe,
    },
    slotRecipes: {
      popup: dialogRecipe,
    },
    
    tokens: {
      fonts: {
        header: { value: '"Inter Tight", sans-serif' },
        body: { value: '"Inter", sans-serif' },  
      },
    },
    semanticTokens: {
      colors: {
        primary: { value: { base: "#8F4A50", _dark: "#FFB2B7" } },
        "surface-tint": { value: { base: "#8F4A50", _dark: "#FFB2B7" } },
        "on-primary": { value: { base: "#FFFFFF", _dark: "#561D24" } },
        "primary-container": { value: { base: "#FFDADB", _dark: "#723339" } },
        "on-primary-container": { value: { base: "#723339", _dark: "#FFDADB" } },
        secondary: { value: { base: "#765658", _dark: "#E6BDBE" } },
        "on-secondary": { value: { base: "#FFFFFF", _dark: "#44292B" } },
        "secondary-container": { value: { base: "#FFDADB", _dark: "#5C3F41" } },
        "on-secondary-container": { value: { base: "#5C3F41", _dark: "#FFDADB" } },
        tertiary: { value: { base: "#775930", _dark: "#E7C08E" } },
        "on-tertiary": { value: { base: "#FFFFFF", _dark: "#432C06" } },
        "tertiary-container": { value: { base: "#FFDDB4", _dark: "#5C421A" } },
        "on-tertiary-container": { value: { base: "#5C421A", _dark: "#FFDDB4" } },
        error: { value: { base: "#BA1A1A", _dark: "#FFB4AB" } },
        "on-error": { value: { base: "#FFFFFF", _dark: "#690005" } },
        "error-container": { value: { base: "#FFDAD6", _dark: "#93000A" } },
        "on-error-container": { value: { base: "#93000A", _dark: "#FFDAD6" } },
        background: { value: { base: "#FFF8F7", _dark: "#1A1112" } },
        "on-background": { value: { base: "#22191A", _dark: "#F0DEDE" } },
        surface: { value: { base: "#FFF8F7", _dark: "#1A1112" } },
        "on-surface": { value: { base: "#22191A", _dark: "#F0DEDE" } },
        "surface-variant": { value: { base: "#F4DDDE", _dark: "#524344" } },
        "on-surface-variant": { value: { base: "#524344", _dark: "#D7C1C2" } },
        outline: { value: { base: "#857373", _dark: "#9F8C8D" } },
        "outline-variant": { value: { base: "#D7C1C2", _dark: "#524344" } },
        shadow: { value: { base: "#000000", _dark: "#000000" } },
        scrim: { value: { base: "#000000", _dark: "#000000" } },
        "inverse-surface": { value: { base: "#382E2E", _dark: "#F0DEDE" } },
        "inverse-on-surface": { value: { base: "#FFEDED", _dark: "#382E2E" } },
        "inverse-primary": { value: { base: "#FFB2B7", _dark: "#8F4A50" } },
        "primary-fixed": { value: { base: "#FFDADB", _dark: "#FFDADB" } },
        "on-primary-fixed": { value: { base: "#3B0811", _dark: "#3B0811" } },
        "primary-fixed-dim": { value: { base: "#FFB2B7", _dark: "#FFB2B7" } },
        "on-primary-fixed-variant": { value: { base: "#723339", _dark: "#723339" } },
        "secondary-fixed": { value: { base: "#FFDADB", _dark: "#FFDADB" } },
        "on-secondary-fixed": { value: { base: "#2C1517", _dark: "#2C1517" } },
        "secondary-fixed-dim": { value: { base: "#E6BDBE", _dark: "#E6BDBE" } },
        "on-secondary-fixed-variant": { value: { base: "#5C3F41", _dark: "#5C3F41" } },
        "tertiary-fixed": { value: { base: "#FFDDB4", _dark: "#FFDDB4" } },
        "on-tertiary-fixed": { value: { base: "#291800", _dark: "#291800" } },
        "tertiary-fixed-dim": { value: { base: "#E7C08E", _dark: "#E7C08E" } },
        "on-tertiary-fixed-variant": { value: { base: "#5C421A", _dark: "#5C421A" } },
        "surface-dim": { value: { base: "#E7D6D6", _dark: "#1A1112" } },
        "surface-bright": { value: { base: "#FFF8F7", _dark: "#413737" } },
        "surface-container-lowest": { value: { base: "#FFFFFF", _dark: "#140C0D" } },
        "surface-container-low": { value: { base: "#FFF0F0", _dark: "#22191A" } },
        "surface-container": { value: { base: "#FCEAEA", _dark: "#271D1E" } },
        "surface-container-high": { value: { base: "#F6E4E4", _dark: "#312828" } },
        "surface-container-highest": { value: { base: "#F0DEDE", _dark: "#3D3233" } },

        // Primary palette
        "primary.0": { value: { base: "#000000", _dark: "#000000" } },
        "primary.5": { value: { base: "#200A0C", _dark: "#200A0C" } },
        "primary.10": { value: { base: "#2D1517", _dark: "#2D1517" } },
        "primary.15": { value: { base: "#381E20", _dark: "#381E20" } },
        "primary.20": { value: { base: "#44292B", _dark: "#44292B" } },
        "primary.25": { value: { base: "#513436", _dark: "#513436" } },
        "primary.30": { value: { base: "#5D3F41", _dark: "#5D3F41" } },
        "primary.35": { value: { base: "#6A4A4C", _dark: "#6A4A4C" } },
        "primary.40": { value: { base: "#775658", _dark: "#775658" } },
        "primary.50": { value: { base: "#926E70", _dark: "#926E70" } },
        "primary.60": { value: { base: "#AD8789", _dark: "#AD8789" } },
        "primary.70": { value: { base: "#CAA1A3", _dark: "#CAA1A3" } },
        "primary.80": { value: { base: "#E7BCBE", _dark: "#E7BCBE" } },
        "primary.90": { value: { base: "#FFDADB", _dark: "#FFDADB" } },
        "primary.95": { value: { base: "#FFECEC", _dark: "#FFECEC" } },
        "primary.98": { value: { base: "#FFF8F7", _dark: "#FFF8F7" } },
        "primary.99": { value: { base: "#FFFBFF", _dark: "#FFFBFF" } },
        "primary.100": { value: { base: "#FFFFFF", _dark: "#FFFFFF" } },

        // Secondary palette
        "secondary.0": { value: { base: "#000000", _dark: "#000000" } },
        "secondary.5": { value: { base: "#170F0F", _dark: "#170F0F" } },
        "secondary.10": { value: { base: "#22191A", _dark: "#22191A" } },
        "secondary.15": { value: { base: "#2D2424", _dark: "#2D2424" } },
        "secondary.20": { value: { base: "#382E2E", _dark: "#382E2E" } },
        "secondary.25": { value: { base: "#433939", _dark: "#433939" } },
        "secondary.30": { value: { base: "#4F4444", _dark: "#4F4444" } },
        "secondary.35": { value: { base: "#5B5050", _dark: "#5B5050" } },
        "secondary.40": { value: { base: "#675C5C", _dark: "#675C5C" } },
        "secondary.50": { value: { base: "#817474", _dark: "#817474" } },
        "secondary.60": { value: { base: "#9B8D8E", _dark: "#9B8D8E" } },
        "secondary.70": { value: { base: "#B6A8A8", _dark: "#B6A8A8" } },
        "secondary.80": { value: { base: "#D3C3C3", _dark: "#D3C3C3" } },
        "secondary.90": { value: { base: "#EFDFDF", _dark: "#EFDFDF" } },
        "secondary.95": { value: { base: "#FEEDED", _dark: "#FEEDED" } },
        "secondary.98": { value: { base: "#FFF8F7", _dark: "#FFF8F7" } },
        "secondary.99": { value: { base: "#FFFBFF", _dark: "#FFFBFF" } },
        "secondary.100": { value: { base: "#FFFFFF", _dark: "#FFFFFF" } },

        // Tertiary palette
        "tertiary.0": { value: { base: "#000000", _dark: "#000000" } },
        "tertiary.5": { value: { base: "#171006", _dark: "#171006" } },
        "tertiary.10": { value: { base: "#221A10", _dark: "#221A10" } },
        "tertiary.15": { value: { base: "#2D2419", _dark: "#2D2419" } },
        "tertiary.20": { value: { base: "#382F23", _dark: "#382F23" } },
        "tertiary.25": { value: { base: "#443A2E", _dark: "#443A2E" } },
        "tertiary.30": { value: { base: "#4F4539", _dark: "#4F4539" } },
        "tertiary.35": { value: { base: "#5C5144", _dark: "#5C5144" } },
        "tertiary.40": { value: { base: "#685C4F", _dark: "#685C4F" } },
        "tertiary.50": { value: { base: "#827567", _dark: "#827567" } },
        "tertiary.60": { value: { base: "#9C8F7F", _dark: "#9C8F7F" } },
        "tertiary.70": { value: { base: "#B7A999", _dark: "#B7A999" } },
        "tertiary.80": { value: { base: "#D3C4B4", _dark: "#D3C4B4" } },
        "tertiary.90": { value: { base: "#F0E0CF", _dark: "#F0E0CF" } },
        "tertiary.95": { value: { base: "#FFEEDD", _dark: "#FFEEDD" } },
        "tertiary.98": { value: { base: "#FFF8F4", _dark: "#FFF8F4" } },
        "tertiary.99": { value: { base: "#FFFBFF", _dark: "#FFFBFF" } },
        "tertiary.100": { value: { base: "#FFFFFF", _dark: "#FFFFFF" } },

        // Neutral palette
        "neutral.0": { value: { base: "#000000", _dark: "#000000" } },
        "neutral.5": { value: { base: "#131010", _dark: "#131010" } },
        "neutral.10": { value: { base: "#1D1B1B", _dark: "#1D1B1B" } },
        "neutral.15": { value: { base: "#282525", _dark: "#282525" } },
        "neutral.20": { value: { base: "#333030", _dark: "#333030" } },
        "neutral.25": { value: { base: "#3E3B3A", _dark: "#3E3B3A" } },
        "neutral.30": { value: { base: "#494646", _dark: "#494646" } },
        "neutral.35": { value: { base: "#555151", _dark: "#555151" } },
        "neutral.40": { value: { base: "#615D5D", _dark: "#615D5D" } },
        "neutral.50": { value: { base: "#7A7676", _dark: "#7A7676" } },
        "neutral.60": { value: { base: "#958F8F", _dark: "#958F8F" } },
        "neutral.70": { value: { base: "#AFAAA9", _dark: "#AFAAA9" } },
        "neutral.80": { value: { base: "#CBC5C5", _dark: "#CBC5C5" } },
        "neutral.90": { value: { base: "#E8E1E0", _dark: "#E8E1E0" } },
        "neutral.95": { value: { base: "#F6EFEE", _dark: "#F6EFEE" } },
        "neutral.98": { value: { base: "#FFF8F7", _dark: "#FFF8F7" } },
        "neutral.99": { value: { base: "#FFFBFF", _dark: "#FFFBFF" } },
        "neutral.100": { value: { base: "#FFFFFF", _dark: "#FFFFFF" } },

        // Neutral-variant palette
        "neutral-variant.0": { value: { base: "#000000", _dark: "#000000" } },
        "neutral-variant.5": { value: { base: "#141010", _dark: "#141010" } },
        "neutral-variant.10": { value: { base: "#1F1A1B", _dark: "#1F1A1B" } },
        "neutral-variant.15": { value: { base: "#292525", _dark: "#292525" } },
        "neutral-variant.20": { value: { base: "#342F2F", _dark: "#342F2F" } },
        "neutral-variant.25": { value: { base: "#403A3A", _dark: "#403A3A" } },
        "neutral-variant.30": { value: { base: "#4B4545", _dark: "#4B4545" } },
        "neutral-variant.35": { value: { base: "#575151", _dark: "#575151" } },
        "neutral-variant.40": { value: { base: "#635D5D", _dark: "#635D5D" } },
        "neutral-variant.50": { value: { base: "#7D7575", _dark: "#7D7575" } },
        "neutral-variant.60": { value: { base: "#978F8F", _dark: "#978F8F" } },
        "neutral-variant.70": { value: { base: "#B2A9A9", _dark: "#B2A9A9" } },
        "neutral-variant.80": { value: { base: "#CEC4C4", _dark: "#CEC4C4" } },
        "neutral-variant.90": { value: { base: "#EAE0E0", _dark: "#EAE0E0" } },
        "neutral-variant.95": { value: { base: "#F9EEEE", _dark: "#F9EEEE" } },
        "neutral-variant.98": { value: { base: "#FFF8F7", _dark: "#FFF8F7" } },
        "neutral-variant.99": { value: { base: "#FFFBFF", _dark: "#FFFBFF" } },
        "neutral-variant.100": { value: { base: "#FFFFFF", _dark: "#FFFFFF" } },
      },
    },
  },
});

export const system = createSystem(defaultConfig, config);
